### PR TITLE
Add automated infra creation using Serverless Framework

### PR DESCRIPTION
**Pull request by HobbyProjects**
Add automated infra deployment using Serverless Framework.

### CODE REVIEW

**Comment by LarryKlugerDS** [comment]
Hi Nima, Instead of a **JSON** environment variable, please use the incoming **Content-Type** to determine if the payload is JSON or XML. Thank you, Larry

**Comment by LarryKlugerDS** [comment]
Also, please update to Node 12.x. 10.x is a little old at this point. Thank you.

**Review by robkkni — APPROVED** [review]
Not an expert but LGTM.

**Comment by HobbyProjects** [comment]
Hi Larry, I am actually going to revert my bug fixes. Let's keep this PR focused on the infra piece only.

**Pull request merged**
